# github repository actions 페이지에 나타날 이름
name: Eatbook-Community-Server

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 변경사항 체크 및 캐싱
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NodeJS Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: 모듈 정보 캐싱
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
      - name: 변경사항이 존재 할 경우 빌드
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - run: npm run build
  # 테스트 job 추가
  deploy:
    needs: build
    name: 배포 시작
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: 도커 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Server 이미지 빌드, 푸쉬
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/eatbook-community:deploy
                   